/**
 * Comprehensive country and city data for ABWcurious Pvt. Ltd.
 * All ~195 sovereign states with major cities and ITU-T E.164 phone codes.
 * Countries sorted alphabetically; cities sorted alphabetically within each country.
 */

export interface Country {
  code: string;
  name: string;
  phoneCode?: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', phoneCode: '+93' },
  { code: 'AL', name: 'Albania', phoneCode: '+355' },
  { code: 'DZ', name: 'Algeria', phoneCode: '+213' },
  { code: 'AD', name: 'Andorra', phoneCode: '+376' },
  { code: 'AO', name: 'Angola', phoneCode: '+244' },
  { code: 'AG', name: 'Antigua and Barbuda', phoneCode: '+1-268' },
  { code: 'AR', name: 'Argentina', phoneCode: '+54' },
  { code: 'AM', name: 'Armenia', phoneCode: '+374' },
  { code: 'AU', name: 'Australia', phoneCode: '+61' },
  { code: 'AT', name: 'Austria', phoneCode: '+43' },
  { code: 'AZ', name: 'Azerbaijan', phoneCode: '+994' },
  { code: 'BS', name: 'Bahamas', phoneCode: '+1-242' },
  { code: 'BH', name: 'Bahrain', phoneCode: '+973' },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880' },
  { code: 'BB', name: 'Barbados', phoneCode: '+1-246' },
  { code: 'BY', name: 'Belarus', phoneCode: '+375' },
  { code: 'BE', name: 'Belgium', phoneCode: '+32' },
  { code: 'BZ', name: 'Belize', phoneCode: '+501' },
  { code: 'BJ', name: 'Benin', phoneCode: '+229' },
  { code: 'BT', name: 'Bhutan', phoneCode: '+975' },
  { code: 'BO', name: 'Bolivia', phoneCode: '+591' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387' },
  { code: 'BW', name: 'Botswana', phoneCode: '+267' },
  { code: 'BR', name: 'Brazil', phoneCode: '+55' },
  { code: 'BN', name: 'Brunei', phoneCode: '+673' },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359' },
  { code: 'BF', name: 'Burkina Faso', phoneCode: '+226' },
  { code: 'BI', name: 'Burundi', phoneCode: '+257' },
  { code: 'CV', name: 'Cabo Verde', phoneCode: '+238' },
  { code: 'KH', name: 'Cambodia', phoneCode: '+855' },
  { code: 'CM', name: 'Cameroon', phoneCode: '+237' },
  { code: 'CA', name: 'Canada', phoneCode: '+1' },
  { code: 'CF', name: 'Central African Republic', phoneCode: '+236' },
  { code: 'TD', name: 'Chad', phoneCode: '+235' },
  { code: 'CL', name: 'Chile', phoneCode: '+56' },
  { code: 'CN', name: 'China', phoneCode: '+86' },
  { code: 'CO', name: 'Colombia', phoneCode: '+57' },
  { code: 'KM', name: 'Comoros', phoneCode: '+269' },
  { code: 'CG', name: 'Congo', phoneCode: '+242' },
  { code: 'CD', name: 'Congo (DRC)', phoneCode: '+243' },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506' },
  { code: 'CI', name: "Côte d'Ivoire", phoneCode: '+225' },
  { code: 'HR', name: 'Croatia', phoneCode: '+385' },
  { code: 'CU', name: 'Cuba', phoneCode: '+53' },
  { code: 'CY', name: 'Cyprus', phoneCode: '+357' },
  { code: 'CZ', name: 'Czech Republic', phoneCode: '+420' },
  { code: 'DK', name: 'Denmark', phoneCode: '+45' },
  { code: 'DJ', name: 'Djibouti', phoneCode: '+253' },
  { code: 'DM', name: 'Dominica', phoneCode: '+1-767' },
  { code: 'DO', name: 'Dominican Republic', phoneCode: '+1-809' },
  { code: 'EC', name: 'Ecuador', phoneCode: '+593' },
  { code: 'EG', name: 'Egypt', phoneCode: '+20' },
  { code: 'SV', name: 'El Salvador', phoneCode: '+503' },
  { code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240' },
  { code: 'ER', name: 'Eritrea', phoneCode: '+291' },
  { code: 'EE', name: 'Estonia', phoneCode: '+372' },
  { code: 'SZ', name: 'Eswatini', phoneCode: '+268' },
  { code: 'ET', name: 'Ethiopia', phoneCode: '+251' },
  { code: 'FJ', name: 'Fiji', phoneCode: '+679' },
  { code: 'FI', name: 'Finland', phoneCode: '+358' },
  { code: 'FR', name: 'France', phoneCode: '+33' },
  { code: 'GA', name: 'Gabon', phoneCode: '+241' },
  { code: 'GM', name: 'Gambia', phoneCode: '+220' },
  { code: 'GE', name: 'Georgia', phoneCode: '+995' },
  { code: 'DE', name: 'Germany', phoneCode: '+49' },
  { code: 'GH', name: 'Ghana', phoneCode: '+233' },
  { code: 'GR', name: 'Greece', phoneCode: '+30' },
  { code: 'GD', name: 'Grenada', phoneCode: '+1-473' },
  { code: 'GT', name: 'Guatemala', phoneCode: '+502' },
  { code: 'GN', name: 'Guinea', phoneCode: '+224' },
  { code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245' },
  { code: 'GY', name: 'Guyana', phoneCode: '+592' },
  { code: 'HT', name: 'Haiti', phoneCode: '+509' },
  { code: 'HN', name: 'Honduras', phoneCode: '+504' },
  { code: 'HU', name: 'Hungary', phoneCode: '+36' },
  { code: 'IS', name: 'Iceland', phoneCode: '+354' },
  { code: 'IN', name: 'India', phoneCode: '+91' },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62' },
  { code: 'IR', name: 'Iran', phoneCode: '+98' },
  { code: 'IQ', name: 'Iraq', phoneCode: '+964' },
  { code: 'IE', name: 'Ireland', phoneCode: '+353' },
  { code: 'IL', name: 'Israel', phoneCode: '+972' },
  { code: 'IT', name: 'Italy', phoneCode: '+39' },
  { code: 'JM', name: 'Jamaica', phoneCode: '+1-876' },
  { code: 'JP', name: 'Japan', phoneCode: '+81' },
  { code: 'JO', name: 'Jordan', phoneCode: '+962' },
  { code: 'KZ', name: 'Kazakhstan', phoneCode: '+7' },
  { code: 'KE', name: 'Kenya', phoneCode: '+254' },
  { code: 'KI', name: 'Kiribati', phoneCode: '+686' },
  { code: 'KP', name: 'Korea (North)', phoneCode: '+850' },
  { code: 'KR', name: 'Korea (South)', phoneCode: '+82' },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965' },
  { code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996' },
  { code: 'LA', name: 'Laos', phoneCode: '+856' },
  { code: 'LV', name: 'Latvia', phoneCode: '+371' },
  { code: 'LB', name: 'Lebanon', phoneCode: '+961' },
  { code: 'LS', name: 'Lesotho', phoneCode: '+266' },
  { code: 'LR', name: 'Liberia', phoneCode: '+231' },
  { code: 'LY', name: 'Libya', phoneCode: '+218' },
  { code: 'LI', name: 'Liechtenstein', phoneCode: '+423' },
  { code: 'LT', name: 'Lithuania', phoneCode: '+370' },
  { code: 'LU', name: 'Luxembourg', phoneCode: '+352' },
  { code: 'MG', name: 'Madagascar', phoneCode: '+261' },
  { code: 'MW', name: 'Malawi', phoneCode: '+265' },
  { code: 'MY', name: 'Malaysia', phoneCode: '+60' },
  { code: 'MV', name: 'Maldives', phoneCode: '+960' },
  { code: 'ML', name: 'Mali', phoneCode: '+223' },
  { code: 'MT', name: 'Malta', phoneCode: '+356' },
  { code: 'MH', name: 'Marshall Islands', phoneCode: '+692' },
  { code: 'MR', name: 'Mauritania', phoneCode: '+222' },
  { code: 'MU', name: 'Mauritius', phoneCode: '+230' },
  { code: 'MX', name: 'Mexico', phoneCode: '+52' },
  { code: 'FM', name: 'Micronesia', phoneCode: '+691' },
  { code: 'MD', name: 'Moldova', phoneCode: '+373' },
  { code: 'MC', name: 'Monaco', phoneCode: '+377' },
  { code: 'MN', name: 'Mongolia', phoneCode: '+976' },
  { code: 'ME', name: 'Montenegro', phoneCode: '+382' },
  { code: 'MA', name: 'Morocco', phoneCode: '+212' },
  { code: 'MZ', name: 'Mozambique', phoneCode: '+258' },
  { code: 'MM', name: 'Myanmar', phoneCode: '+95' },
  { code: 'NA', name: 'Namibia', phoneCode: '+264' },
  { code: 'NR', name: 'Nauru', phoneCode: '+674' },
  { code: 'NP', name: 'Nepal', phoneCode: '+977' },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31' },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64' },
  { code: 'NI', name: 'Nicaragua', phoneCode: '+505' },
  { code: 'NE', name: 'Niger', phoneCode: '+227' },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234' },
  { code: 'MK', name: 'North Macedonia', phoneCode: '+389' },
  { code: 'NO', name: 'Norway', phoneCode: '+47' },
  { code: 'OM', name: 'Oman', phoneCode: '+968' },
  { code: 'PK', name: 'Pakistan', phoneCode: '+92' },
  { code: 'PW', name: 'Palau', phoneCode: '+680' },
  { code: 'PS', name: 'Palestine', phoneCode: '+970' },
  { code: 'PA', name: 'Panama', phoneCode: '+507' },
  { code: 'PG', name: 'Papua New Guinea', phoneCode: '+675' },
  { code: 'PY', name: 'Paraguay', phoneCode: '+595' },
  { code: 'PE', name: 'Peru', phoneCode: '+51' },
  { code: 'PH', name: 'Philippines', phoneCode: '+63' },
  { code: 'PL', name: 'Poland', phoneCode: '+48' },
  { code: 'PT', name: 'Portugal', phoneCode: '+351' },
  { code: 'QA', name: 'Qatar', phoneCode: '+974' },
  { code: 'RO', name: 'Romania', phoneCode: '+40' },
  { code: 'RU', name: 'Russia', phoneCode: '+7' },
  { code: 'RW', name: 'Rwanda', phoneCode: '+250' },
  { code: 'KN', name: 'Saint Kitts and Nevis', phoneCode: '+1-869' },
  { code: 'LC', name: 'Saint Lucia', phoneCode: '+1-758' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', phoneCode: '+1-784' },
  { code: 'WS', name: 'Samoa', phoneCode: '+685' },
  { code: 'SM', name: 'San Marino', phoneCode: '+378' },
  { code: 'ST', name: 'Sao Tome and Principe', phoneCode: '+239' },
  { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966' },
  { code: 'SN', name: 'Senegal', phoneCode: '+221' },
  { code: 'RS', name: 'Serbia', phoneCode: '+381' },
  { code: 'SC', name: 'Seychelles', phoneCode: '+248' },
  { code: 'SL', name: 'Sierra Leone', phoneCode: '+232' },
  { code: 'SG', name: 'Singapore', phoneCode: '+65' },
  { code: 'SK', name: 'Slovakia', phoneCode: '+421' },
  { code: 'SI', name: 'Slovenia', phoneCode: '+386' },
  { code: 'SB', name: 'Solomon Islands', phoneCode: '+677' },
  { code: 'SO', name: 'Somalia', phoneCode: '+252' },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27' },
  { code: 'SS', name: 'South Sudan', phoneCode: '+211' },
  { code: 'ES', name: 'Spain', phoneCode: '+34' },
  { code: 'LK', name: 'Sri Lanka', phoneCode: '+94' },
  { code: 'SD', name: 'Sudan', phoneCode: '+249' },
  { code: 'SR', name: 'Suriname', phoneCode: '+597' },
  { code: 'SE', name: 'Sweden', phoneCode: '+46' },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41' },
  { code: 'SY', name: 'Syria', phoneCode: '+963' },
  { code: 'TW', name: 'Taiwan', phoneCode: '+886' },
  { code: 'TJ', name: 'Tajikistan', phoneCode: '+992' },
  { code: 'TZ', name: 'Tanzania', phoneCode: '+255' },
  { code: 'TH', name: 'Thailand', phoneCode: '+66' },
  { code: 'TL', name: 'Timor-Leste', phoneCode: '+670' },
  { code: 'TG', name: 'Togo', phoneCode: '+228' },
  { code: 'TO', name: 'Tonga', phoneCode: '+676' },
  { code: 'TT', name: 'Trinidad and Tobago', phoneCode: '+1-868' },
  { code: 'TN', name: 'Tunisia', phoneCode: '+216' },
  { code: 'TR', name: 'Turkey', phoneCode: '+90' },
  { code: 'TM', name: 'Turkmenistan', phoneCode: '+993' },
  { code: 'TV', name: 'Tuvalu', phoneCode: '+688' },
  { code: 'UG', name: 'Uganda', phoneCode: '+256' },
  { code: 'UA', name: 'Ukraine', phoneCode: '+380' },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971' },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44' },
  { code: 'US', name: 'United States', phoneCode: '+1' },
  { code: 'UY', name: 'Uruguay', phoneCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan', phoneCode: '+998' },
  { code: 'VU', name: 'Vanuatu', phoneCode: '+678' },
  { code: 'VA', name: 'Vatican City', phoneCode: '+379' },
  { code: 'VE', name: 'Venezuela', phoneCode: '+58' },
  { code: 'VN', name: 'Vietnam', phoneCode: '+84' },
  { code: 'YE', name: 'Yemen', phoneCode: '+967' },
  { code: 'ZM', name: 'Zambia', phoneCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', phoneCode: '+263' },
];

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  AF: ['Herat', 'Kabul', 'Kandahar', 'Kunduz', 'Mazar-i-Sharif', 'Taloqan'],
  AL: ['Berat', 'Durrës', 'Elbasan', 'Fier', 'Korçë', 'Shkodër', 'Tirana', 'Vlorë'],
  DZ: ['Algiers', 'Annaba', 'Batna', 'Béjaïa', 'Blida', 'Constantine', 'Oran', 'Sétif', 'Tlemcen'],
  AD: ['Andorra la Vella', 'Canillo', 'Encamp', 'Escaldes-Engordany', 'La Massana', 'Ordino', 'Sant Julià de Lòria'],
  AO: ['Benguela', 'Cabinda', 'Huambo', 'Kuito', 'Luanda', 'Lubango', 'Malanje', 'Namibe'],
  AG: ['St. John\'s'],
  AR: ['Buenos Aires', 'Córdoba', 'La Plata', 'Mar del Plata', 'Mendoza', 'Rosario', 'Salta', 'San Miguel de Tucumán', 'Santa Fe'],
  AM: ['Armavir', 'Artashat', 'Gyumri', 'Hrazdan', 'Kapan', 'Stepanakert', 'Vanadzor', 'Yerevan'],
  AU: ['Adelaide', 'Brisbane', 'Canberra', 'Darwin', 'Gold Coast', 'Hobart', 'Melbourne', 'Perth', 'Sydney', 'Wollongong'],
  AT: ['Graz', 'Innsbruck', 'Klagenfurt', 'Linz', 'Salzburg', 'Vienna', 'Villach', 'Wels'],
  AZ: ['Baku', 'Ganja', 'Lankaran', 'Mingachevir', 'Nakhchivan', 'Shirvan', 'Sumqayit', 'Yevlakh'],
  BS: ['Freeport', 'Nassau'],
  BH: ['Madinat Hamad', 'Madinat Isa', 'Manama', 'Muharraq', 'Riffa'],
  BD: ['Chittagong', 'Comilla', 'Cox\'s Bazar', 'Dhaka', 'Dinajpur', 'Gazipur', 'Khulna', 'Narayanganj', 'Rajshahi', 'Rangpur', 'Sylhet', 'Tongi'],
  BB: ['Bridgetown', 'Holetown', 'Oistins', 'Speightstown'],
  BY: ['Brest', 'Gomel', 'Grodno', 'Minsk', 'Mogilev', 'Vitebsk'],
  BE: ['Antwerp', 'Bruges', 'Brussels', 'Charleroi', 'Ghent', 'Leuven', 'Liège', 'Namur'],
  BZ: ['Belmopan', 'Belize City', 'Orange Walk', 'San Ignacio'],
  BJ: ['Abomey-Calavi', 'Cotonou', 'Djougou', 'Parakou', 'Porto-Novo'],
  BT: ['Gelephu', 'Mongar', 'Paro', 'Phuentsholing', 'Punakha', 'Samdrup Jongkhar', 'Thimphu', 'Trashigang', 'Wangdue Phodrang'],
  BO: ['Cochabamba', 'El Alto', 'La Paz', 'Oruro', 'Potosí', 'Santa Cruz de la Sierra', 'Sucre', 'Tarija'],
  BA: ['Banja Luka', 'Bijeljina', 'Brčko', 'Mostar', 'Sarajevo', 'Tuzla', 'Zenica'],
  BW: ['Francistown', 'Gaborone', 'Maun', 'Molepolole', 'Serowe'],
  BR: ['Belo Horizonte', 'Brasília', 'Campinas', 'Curitiba', 'Fortaleza', 'Manaus', 'Porto Alegre', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo'],
  BN: ['Bandar Seri Begawan', 'Belait', 'Kuala Belait', 'Seria', 'Tutong'],
  BG: ['Burgas', 'Plovdiv', 'Ruse', 'Sofia', 'Stara Zagora', 'Varna', 'Veliko Tarnovo'],
  BF: ['Bobo-Dioulasso', 'Koudougou', 'Ouagadougou', 'Ouahigouya'],
  BI: ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi', 'Ruyigi'],
  CV: ['Mindelo', 'Praia', 'Santa Maria', 'São Filipe'],
  KH: ['Battambang', 'Kampong Cham', 'Kampong Som', 'Phnom Penh', 'Siem Reap', 'Sihanoukville'],
  CM: ['Bafoussam', 'Bamenda', 'Douala', 'Garoua', 'Maroua', 'Yaoundé'],
  CA: ['Calgary', 'Edmonton', 'Halifax', 'Hamilton', 'Mississauga', 'Montreal', 'Ottawa', 'Quebec City', 'Toronto', 'Vancouver', 'Winnipeg'],
  CF: ['Bangui', 'Bambari', 'Berbérati', 'Bossangoa', 'Mbaïki'],
  TD: ['Abéché', 'Doba', 'Moundou', 'N\'Djamena', 'Sarh'],
  CL: ['Antofagasta', 'Concepción', 'Puente Alto', 'Santiago', 'Valparaíso', 'Viña del Mar'],
  CN: ['Beijing', 'Changsha', 'Chengdu', 'Chongqing', 'Dongguan', 'Foshan', 'Guangzhou', 'Hangzhou', 'Harbin', 'Jinan', 'Kunming', 'Nanjing', 'Qingdao', 'Shanghai', 'Shenzhen', 'Shenyang', 'Suzhou', 'Tianjin', 'Wuhan', 'Xi\'an', 'Zhengzhou'],
  CO: ['Barranquilla', 'Bogotá', 'Bucaramanga', 'Cali', 'Cartagena', 'Medellín', 'Pereira'],
  KM: ['Moroni', 'Moutsamoudou', 'Fomboni'],
  CG: ['Brazzaville', 'Dolisie', 'Pointe-Noire'],
  CD: ['Kananga', 'Kikwit', 'Kinshasa', 'Kisangani', 'Lubumbashi', 'Mbuji-Mayi', 'Mbandaka'],
  CR: ['Alajuela', 'Cartago', 'Heredia', 'Limón', 'Puntarenas', 'San José'],
  CI: ['Abidjan', 'Bouaké', 'Daloa', 'Korhogo', 'San-Pédro', 'Yamoussoukro'],
  HR: ['Dubrovnik', 'Osijek', 'Rijeka', 'Split', 'Zadar', 'Zagreb'],
  CU: ['Camagüey', 'Havana', 'Holguín', 'Santa Clara', 'Santiago de Cuba'],
  CY: ['Kyrenia', 'Larnaca', 'Limassol', 'Nicosia', 'Paphos'],
  CZ: ['Brno', 'Liberec', 'Olomouc', 'Ostrava', 'Pardubice', 'Plzeň', 'Prague', 'Ústí nad Labem'],
  DK: ['Aalborg', 'Aarhus', 'Copenhagen', 'Esbjerg', 'Odense', 'Randers', 'Roskilde'],
  DJ: ['Ali Sabieh', 'Djibouti', 'Tadjourah'],
  DM: ['Roseau', 'Portsmouth'],
  DO: ['Boca Chica', 'Higüey', 'La Romana', 'Puerto Plata', 'Punta Cana', 'Santiago de los Caballeros', 'Santo Domingo'],
  EC: ['Cuenca', 'Guayaquil', 'Loja', 'Machala', 'Quito', 'Santo Domingo'],
  EG: ['Alexandria', 'Aswan', 'Cairo', 'Giza', 'Hurghada', 'Luxor', 'Mansoura', 'Sharm El Sheikh', 'Tanta'],
  SV: ['Santa Ana', 'San Miguel', 'San Salvador', 'Soyapango', 'Sonsonte'],
  GQ: ['Bata', 'Malabo'],
  ER: ['Asmara', 'Assab', 'Keren', 'Massawa'],
  EE: ['Narva', 'Pärnu', 'Tallinn', 'Tartu', 'Viljandi'],
  SZ: ['Manzini', 'Mbabane', 'Nhlangano', 'Siteki'],
  ET: ['Addis Ababa', 'Adama', 'Bahir Dar', 'Dire Dawa', 'Gondar', 'Hawassa', 'Jimma', 'Mekelle'],
  FJ: ['Lautoka', 'Nadi', 'Suva'],
  FI: ['Espoo', 'Helsinki', 'Lahti', 'Oulu', 'Tampere', 'Turku', 'Vantaa'],
  FR: ['Bordeaux', 'Lille', 'Lyon', 'Marseille', 'Montpellier', 'Nantes', 'Nice', 'Paris', 'Rennes', 'Strasbourg', 'Toulouse'],
  GA: ['Franceville', 'Libreville', 'Port-Gentil'],
  GM: ['Banjul', 'Brikama', 'Farafenni', 'Serrekunda'],
  GE: ['Batumi', 'Gori', 'Kutaisi', 'Rustavi', 'Sukhumi', 'Tbilisi', 'Zugdidi'],
  DE: ['Berlin', 'Bremen', 'Cologne', 'Dortmund', 'Dresden', 'Düsseldorf', 'Essen', 'Frankfurt', 'Hamburg', 'Hannover', 'Leipzig', 'Munich', 'Nuremberg', 'Stuttgart'],
  GH: ['Accra', 'Ashaiman', 'Cape Coast', 'Kumasi', 'Obuasi', 'Sekondi-Takoradi', 'Tamale', 'Tema'],
  GR: ['Athens', 'Heraklion', 'Larissa', 'Patras', 'Piraeus', 'Thessaloniki', 'Volos'],
  GD: ['St. George\'s', 'Gouyave', 'Grenville'],
  GT: ['Guatemala City', 'Mixco', 'Quetzaltenango', 'Escuintla', 'Villa Nueva'],
  GN: ['Conakry', 'Kankan', 'Kindia', 'Nzérékoré'],
  GW: ['Bafatá', 'Bissau', 'Gabú'],
  GY: ['Georgetown', 'Linden', 'New Amsterdam'],
  HT: ['Cap-Haïtien', 'Carrefour', 'Delmas', 'Pétion-Ville', 'Port-au-Prince'],
  HN: ['Choloma', 'Comayagua', 'La Ceiba', 'San Pedro Sula', 'Tegucigalpa'],
  HU: ['Budapest', 'Debrecen', 'Győr', 'Kecskemét', 'Miskolc', 'Pécs', 'Szeged', 'Székesfehérvár'],
  IS: ['Akureyri', 'Hafnarfjörður', 'Keflavík', 'Kópavogur', 'Reykjavík'],
  IN: [
    'Ahmedabad', 'Agra', 'Allahabad', 'Amritsar', 'Aurangabad',
    'Bangalore', 'Bhopal', 'Bhubaneswar', 'Chandigarh', 'Chennai',
    'Coimbatore', 'Dehradun', 'Delhi', 'Faridabad', 'Ghaziabad',
    'Gurgaon', 'Guwahati', 'Howrah', 'Hyderabad', 'Indore',
    'Jaipur', 'Jabalpur', 'Jodhpur', 'Kanpur', 'Kochi',
    'Kolkata', 'Kozhikode', 'Lucknow', 'Ludhiana', 'Madurai',
    'Meerut', 'Mumbai', 'Nagpur', 'Nashik', 'Navi Mumbai',
    'Noida', 'Patna', 'Pimpri-Chinchwad', 'Pune', 'Raipur',
    'Rajkot', 'Ranchi', 'Surat', 'Thane', 'Thiruvananthapuram',
    'Vadodara', 'Varanasi', 'Vijayawada', 'Visakhapatnam', 'Vellore',
  ],
  ID: ['Bandung', 'Bekasi', 'Depok', 'Jakarta', 'Makassar', 'Medan', 'Palembang', 'Semarang', 'Surabaya', 'Tangerang'],
  IR: ['Esfahan', 'Karaj', 'Mashhad', 'Qom', 'Shiraz', 'Tabriz', 'Tehran'],
  IQ: ['Baghdad', 'Basra', 'Erbil', 'Kirkuk', 'Mosul', 'Najaf', 'Sulaymaniyah'],
  IE: ['Cork', 'Dublin', 'Dundalk', 'Galway', 'Limerick', 'Waterford'],
  IL: ['Beersheba', 'Haifa', 'Jerusalem', 'Netanya', 'Petah Tikva', 'Rishon LeZion', 'Tel Aviv'],
  IT: ['Bari', 'Bologna', 'Catania', 'Florence', 'Genoa', 'Messina', 'Milan', 'Naples', 'Palermo', 'Rome', 'Turin', 'Venice'],
  JM: ['Kingston', 'Montego Bay', 'Portmore', 'Spanish Town'],
  JP: ['Chiba', 'Fukuoka', 'Hiroshima', 'Kobe', 'Kyoto', 'Nagoya', 'Osaka', 'Saitama', 'Sapporo', 'Sendai', 'Tokyo', 'Yokohama'],
  JO: ['Amman', 'Irbid', 'Jerash', 'Zarqa'],
  KZ: ['Almaty', 'Astana', 'Aktobe', 'Karaganda', 'Pavlodar', 'Shymkent'],
  KE: ['Eldoret', 'Kisumu', 'Mombasa', 'Nakuru', 'Nairobi', 'Thika'],
  KI: ['South Tarawa'],
  KP: ['Chongjin', 'Hamhung', 'Kaesong', 'Nampo', 'Pyongyang', 'Sinuiju'],
  KR: ['Busan', 'Daegu', 'Daejeon', 'Gwangju', 'Incheon', 'Sejong', 'Seoul', 'Suwon', 'Ulsan'],
  KW: ['Al Jahra', 'Al Ahmadi', 'Hawalli', 'Kuwait City', 'Mubarak Al-Kabeer'],
  KG: ['Bishkek', 'Jalal-Abad', 'Karakol', 'Osh', 'Tokmok'],
  LA: ['Luang Prabang', 'Pakse', 'Savannakhet', 'Vientiane'],
  LV: ['Daugavpils', 'Jelgava', 'Jūrmala', 'Liepāja', 'Riga', 'Ventspils'],
  LB: ['Beirut', 'Sidon', 'Tripoli', 'Tyre', 'Zahle'],
  LS: ['Maseru', 'Teyateyaneng'],
  LR: ['Gbarnga', 'Kakata', 'Monrovia', 'Paynesville'],
  LY: ['Benghazi', 'Misrata', 'Tripoli', 'Zawiya'],
  LI: ['Schaan', 'Vaduz'],
  LT: ['Kaunas', 'Klaipėda', 'Panevėžys', 'Šiauliai', 'Vilnius'],
  LU: ['Differdange', 'Dudelange', 'Esch-sur-Alzette', 'Luxembourg'],
  MG: ['Antananarivo', 'Antsirabe', 'Fianarantsoa', 'Mahajanga', 'Toamasina'],
  MW: ['Blantyre', 'Lilongwe', 'Mzuzu', 'Zomba'],
  MY: ['George Town', 'Ipoh', 'Johor Bahru', 'Kuala Lumpur', 'Kuching', 'Malacca', 'Petaling Jaya', 'Shah Alam'],
  MV: ['Addu City', 'Malé'],
  ML: ['Bamako', 'Gao', 'Kayedes', 'Mopti', 'Sikasso', 'Tombouctou'],
  MT: ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Rabat', 'Sliema'],
  MH: ['Majuro', 'Ebeye'],
  MR: ['Nouakchott', 'Nouadhibou', 'Rosso', 'Zouérat'],
  MU: ['Curepipe', 'Port Louis', 'Quatre Bornes', 'Vacoas'],
  MX: ['Cancún', 'Guadalajara', 'León', 'Mérida', 'Mexico City', 'Monterrey', 'Puebla', 'Querétaro', 'Tijuana', 'Toluca'],
  FM: ['Kolonia', 'Weno'],
  MD: ['Bălți', 'Chișinău', 'Tiraspol'],
  MC: ['Monte Carlo', 'La Condamine', 'Fontvieille'],
  MN: ['Darkhan', 'Erdenet', 'Kharkhorin', 'Ulaanbaatar'],
  ME: ['Bar', 'Budva', 'Herceg Novi', 'Kotor', 'Nikšić', 'Podgorica', 'Tivat'],
  MA: ['Casablanca', 'Fez', 'Marrakech', 'Meknes', 'Rabat', 'Tangier', 'Agadir'],
  MZ: ['Beira', 'Chimoio', 'Maputo', 'Matola', 'Nampula', 'Quelimane'],
  MM: ['Bago', 'Mandalay', 'Mawlamyine', 'Monywa', 'Naypyidaw', 'Taunggyi', 'Yangon'],
  NA: ['Oshikati', 'Rundu', 'Swakopmund', 'Walvis Bay', 'Windhoek'],
  NR: ['Yaren'],
  NP: ['Biratnagar', 'Birgunj', 'Dharan', 'Janakpur', 'Kathmandu', 'Lalitpur', 'Pokhara', 'Bharatpur', 'Bhaktapur'],
  NL: ['Amsterdam', 'Eindhoven', 'Groningen', 'Rotterdam', 'The Hague', 'Tilburg', 'Utrecht'],
  NZ: ['Auckland', 'Christchurch', 'Dunedin', 'Hamilton', 'Palmerston North', 'Wellington'],
  NI: ['Chinandega', 'Estelí', 'Granada', 'León', 'Managua', 'Masaya', 'Matagalpa'],
  NE: ['Agadez', 'Diffa', 'Maradi', 'Niamey', 'Tahoua', 'Zinder'],
  NG: ['Abuja', 'Benin City', 'Ibadan', 'Kaduna', 'Kano', 'Lagos', 'Port Harcourt'],
  MK: ['Bitola', 'Kumanovo', 'Ohrid', 'Prilep', 'Skopje'],
  NO: ['Bergen', 'Oslo', 'Stavanger', 'Tromsø', 'Trondheim'],
  OM: ['Muscat', 'Salalah', 'Seeb', 'Sohar', 'Sur'],
  PK: ['Faisalabad', 'Islamabad', 'Karachi', 'Lahore', 'Multan', 'Peshawar', 'Quetta', 'Rawalpindi', 'Sialkot'],
  PW: ['Koror', 'Melekeok'],
  PS: ['Bethlehem', 'Gaza', 'Hebron', 'Nablus', 'Ramallah'],
  PA: ['Colón', 'David', 'Panama City', 'Tocumen'],
  PG: ['Lae', 'Madang', 'Mount Hagen', 'Port Moresby'],
  PY: ['Asunción', 'Ciudad del Este', 'Encarnación', 'Luque', 'San Lorenzo'],
  PE: ['Arequipa', 'Cusco', 'Lima', 'Piura', 'Trujillo'],
  PH: ['Cebu City', 'Davao', 'Makati', 'Manila', 'Quezon City', 'Taguig', 'Zamboanga'],
  PL: ['Gdańsk', 'Kraków', 'Łódź', 'Lublin', 'Poznań', 'Szczecin', 'Warsaw', 'Wrocław'],
  PT: ['Braga', 'Coimbra', 'Faro', 'Funchal', 'Lisbon', 'Porto', 'Setúbal'],
  QA: ['Al Wakrah', 'Al Khor', 'Doha', 'Lusail', 'Mesaieed'],
  RO: ['Brașov', 'Cluj-Napoca', 'Constanța', 'Craiova', 'Iași', 'Timișoara', 'Bucharest'],
  RU: ['Cheboksary', 'Kazan', 'Krasnodar', 'Moscow', 'Nizhny Novgorod', 'Novosibirsk', 'Rostov-on-Don', 'Samara', 'Saint Petersburg', 'Sochi', 'Yekaterinburg', 'Vladivostok'],
  RW: ['Butare', 'Gisenyi', 'Kigali', 'Musanze', 'Ruhengeri'],
  KN: ['Basseterre', 'Charlestown'],
  LC: ['Castries', 'Gros Islet', 'Soufrière', 'Vieux Fort'],
  VC: ['Kingstown', 'Arnold Vale', 'Georgetown'],
  WS: ['Apia'],
  SM: ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano'],
  ST: ['São Tomé'],
  SA: ['Abha', 'Dammam', 'Jeddah', 'Mecca', 'Medina', 'Riyadh', 'Tabuk', 'Taif'],
  SN: ['Dakar', 'Kaolack', 'Saint-Louis', 'Thiès', 'Touba', 'Ziguinchor'],
  RS: ['Belgrade', 'Kragujevac', 'Niš', 'Novi Sad', 'Subotica'],
  SC: ['Victoria'],
  SL: ['Bo', 'Freetown', 'Kenema', 'Makeni'],
  SG: ['Singapore'],
  SK: ['Bratislava', 'Košice', 'Nitra', 'Prešov', 'Žilina'],
  SI: ['Kranj', 'Ljubljana', 'Maribor', 'Novo Mesto'],
  SB: ['Auki', 'Gizo', 'Honiara'],
  SO: ['Bosaso', 'Hargeisa', 'Kismayo', 'Mogadishu'],
  ZA: ['Cape Town', 'Durban', 'Johannesburg', 'Pretoria', 'Port Elizabeth', 'Stellenbosch', 'Soweto'],
  SS: ['Juba', 'Malakal', 'Wau', 'Yei'],
  ES: ['Alicante', 'Barcelona', 'Bilbao', 'Málaga', 'Madrid', 'Palma', 'Seville', 'Valencia', 'Zaragoza'],
  LK: ['Colombo', 'Galle', 'Jaffna', 'Kandy', 'Negombo', 'Trincomalee'],
  SD: ['Al Obeid', 'Khartoum', 'Kosti', 'Nyala', 'Port Sudan'],
  SR: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'],
  SE: ['Gothenburg', 'Malmö', 'Stockholm', 'Uppsala', 'Umeå', 'Linköping'],
  CH: ['Basel', 'Bern', 'Geneva', 'Lausanne', 'Lucerne', 'Zurich', 'Winterthur'],
  SY: ['Aleppo', 'Damascus', 'Hama', 'Homs', 'Latakia'],
  TW: ['Hsinchu', 'Kaohsiung', 'Taichung', 'Tainan', 'Taipei', 'Taoyuan'],
  TJ: ['Dushanbe', 'Khujand', 'Kulob', 'Khorugh'],
  TZ: ['Arusha', 'Dar es Salaam', 'Dodoma', 'Mwanza', 'Zanzibar City'],
  TH: ['Bangkok', 'Chiang Mai', 'Hat Yai', 'Nakhon Ratchasima', 'Pattaya', 'Phuket', 'Udon Thani'],
  TL: ['Dili', 'Baucau', 'Maliana'],
  TG: ['Lomé', 'Kara', 'Sokodé', 'Atakpamé'],
  TO: ['Nuku\'alofa'],
  TT: ['Chaguanas', 'Port of Spain', 'San Fernando', 'Arima'],
  TN: ['Bizerte', 'Gabès', 'Kairouan', 'Sfax', 'Sousse', 'Tunis'],
  TR: ['Adana', 'Ankara', 'Antalya', 'Bursa', 'Gaziantep', 'Istanbul', 'Izmir', 'Konya', 'Mersin'],
  TM: ['Ashgabat', 'Turkmenabat', 'Dashoguz', 'Mary'],
  TV: ['Funafuti'],
  UG: ['Entebbe', 'Gulu', 'Jinja', 'Kampala', 'Lira', 'Mbarara'],
  UA: ['Dnipro', 'Donetsk', 'Kharkiv', 'Kyiv', 'Lviv', 'Odesa', 'Zaporizhzhia'],
  AE: ['Abu Dhabi', 'Ajman', 'Al Ain', 'Dubai', 'Fujairah', 'Ras Al Khaimah', 'Sharjah', 'Umm Al Quwain'],
  GB: ['Birmingham', 'Bristol', 'Edinburgh', 'Glasgow', 'Leeds', 'Liverpool', 'London', 'Manchester', 'Newcastle', 'Nottingham', 'Sheffield'],
  US: [
    'Albuquerque', 'Atlanta', 'Austin', 'Baltimore', 'Boston',
    'Charlotte', 'Chicago', 'Columbus', 'Dallas', 'Denver',
    'Detroit', 'Houston', 'Indianapolis', 'Jacksonville', 'Kansas City',
    'Las Vegas', 'Los Angeles', 'Louisville', 'Miami', 'Minneapolis',
    'Nashville', 'New York', 'Oklahoma City', 'Philadelphia', 'Phoenix',
    'Pittsburgh', 'Portland', 'Raleigh', 'San Antonio', 'San Diego',
    'San Francisco', 'San Jose', 'Seattle', 'Washington DC',
  ],
  UY: ['Montevideo', 'Paysandú', 'Salto', 'Maldonado'],
  UZ: ['Bukhara', 'Fergana', 'Namangan', 'Samarkand', 'Tashkent'],
  VU: ['Port Vila', 'Luganville'],
  VA: ['Vatican City'],
  VE: ['Caracas', 'Ciudad Guayana', 'Maracaibo', 'Maracay', 'Valencia'],
  VN: ['Can Tho', 'Da Nang', 'Haiphong', 'Hanoi', 'Ho Chi Minh City', 'Hue', 'Nha Trang'],
  YE: ['Aden', 'Sana\'a', 'Taiz', 'Al Hudaydah'],
  ZM: ['Kitwe', 'Lusaka', 'Ndola', 'Kabwe', 'Chingola'],
  ZW: ['Bulawayo', 'Chitungwiza', 'Harare', 'Mutare', 'Gweru'],
};
